### ISSUE TITLE
Windows not supported

### ISSUE THREAD

**Issue by navono** [sagikazarmark/modern-go-application#113]
Any possible to support Windows?

**Comment by sagikazarmark** [comment]
Although the Makefile and the scripts are Linux/Mac specific, I think the application should compile on windows as well (with the exception of tableflip).

**Comment by navono** [comment]
yes, with the `tableflip`, it occurs below errors:
```
C:\Users\user\go\pkg\mod\github.com\cloudflare\tableflip@v1.0.0\env.go:13:2: cannot use syscall.CloseOnExec (type func(syscall.Handle)) as type func(int) in field value
C:\Users\user\go\pkg\mod\github.com\cloudflare\tableflip@v1.0.0\fds.go:344:36: not enough arguments in call to syscall.Syscall
C:\Users\user\go\pkg\mod\github.com\cloudflare\tableflip@v1.0.0\fds.go:344:37: undefined: syscall.SYS_FCNTL
C:\Users\user\go\pkg\mod\github.com\cloudflare\tableflip@v1.0.0\fds.go:344:60: undefined: syscall.F_DUPFD_CLOEXEC
```

Is there any other way to replace `tableflip` ?

**Comment by sagikazarmark** [comment]
You can easily remove it from `main.go`. There is no alternative library for it that I know of.

**Comment by navono** [comment]
After some dig about upgrade in golang, there is really no good solution on the windows platform.
Thank you for response.
