### ISSUE TITLE
How to use OpenAPI

### ISSUE THREAD

**Issue by atomicleads** [sagikazarmark/modern-go-application#125]
There is a folder .gen/api/openapi with generated code. I do not see it's used somewhere. What it is for? Could you please suggest a way how to use it ?

**Comment by sagikazarmark** [comment]
It _was_ used for the returned models from the Todo API, but I optimized it to return domain objects directly.

Here is a version that used the generated models: https://github.com/sagikazarmark/modern-go-application/blob/5bf6e3d84e705ddc322b9ff8585595cc3b78c57f/internal/app/mga/todo/tododriver/transport_http.go#L69

Ideally you should be fine with the domain response models, but that's not always the case.

I left the generated models in the application to demonstrate how code generation works for OpenAPI.

**Comment by atomicleads** [comment]
Thank you for the quick response.
I'm asking, because i do not like an idea to create decode function for each endpoint. I can understand it for a small app like a todo app, but how you envision it for a larger apps ?

**Comment by sagikazarmark** [comment]
It allows you to keep your business logic independent from the transport. Most of the time it's just boilerplate code.

I would strongly advise against using OpenAPI generated models in your business logic in a Go kit application. That creates a dependency on a higher level.

Here is a real life example using Go kit: https://github.com/micromdm/micromdm

**Comment by atomicleads** [comment]
Thank you! You reference is very useful!
