### ISSUE TITLE
Why MySQL

### ISSUE THREAD

**Issue by atomicleads** [sagikazarmark/modern-go-application#126]
Could you please share reasons why you decided to use MySQL for this project?

**Comment by sagikazarmark** [comment]
I didn't have any specific reasons. I use MySQL/Postgres most of the time, so it seemed natural to include one of those.

For some time now I'm actually thinking about refactoring that part in a way that supports multiple database backends.

I also want to try Facebook's ent: https://github.com/facebookincubator/ent

For the time being it's MySQL only.

**Comment by atomicleads** [comment]
Thank you, solid response! 
Not related, but could you please suggest how to implement jwt auth and protect some endpoints. Any references to the projects that implemented that are welcome.  micromdm project is good reference to get into go-kit, but i not found any jwt related code there. Btw they are using sqlx and squirrel and boltdb for some operations.

**Comment by sagikazarmark** [comment]
Go-kit actually comes with JWT package and docs about using it: https://github.com/go-kit/kit/tree/master/auth/jwt

Unfortunately I don't have an example at hand that actually uses it.

**Comment by sagikazarmark** [comment]
Pro tip: look for applications with go-kit topic on GitHub: https://github.com/topics/go-kit
