### ISSUE TITLE
Sync dependencies fails

### ISSUE THREAD

**Issue by Dmdv** [sagikazarmark/modern-go-application#150]
The application was generated with 
```
? Package name (/home/dima/develop/go-app1) github.com/dmdv/go-app1
? Project name (go-app1) 
? Binary name (go-app1) 
? Application name (go-app1) 
? Friendly application name (Go App1) Modern Go Application
? Update README (Y/n) Y
? Remove init script (y/N) n
```

When I tried to sync dependencies, I got the following error

```
go: finding module for package github.com/dmdv/go-app1/internal/app/go-app1
go: finding module for package github.com/dmdv/go-app1/internal/app/go-app1/todo/tododriver
github.com/dmdv/go-app1/cmd/go-app1 imports
	github.com/dmdv/go-app1/internal/app/go-app1: no matching versions for query "latest"
github.com/dmdv/go-app1/cmd/go-app1 imports
	github.com/dmdv/go-app1/internal/app/go-app1/todo/tododriver: no matching versions for query "latest"
github.com/dmdv/go-app1/internal/app/mga imports
	github.com/sagikazarmark/todobackend-go-kit/todo/tododriver imports
	github.com/sagikazarmark/todobackend-go-kit/internal/.generated/api/v1/graphql: malformed import path "github.com/sagikazarmark/todobackend-go-kit/internal/.generated/api/v1/graphql": leading dot in path element
github.com/dmdv/go-app1/internal/app/mga imports
	github.com/sagikazarmark/todobackend-go-kit/todo/tododriver imports
	github.com/sagikazarmark/todobackend-go-kit/internal/.generated/api/v1/rest/go: malformed import path "github.com/sagikazarmark/todobackend-go-kit/internal/.generated/api/v1/rest/go": leading dot in path element
```

![image](https://user-images.githubusercontent.com/805238/111081494-a5a7a680-8514-11eb-8e8b-e2044a96bcd8.png)

And script generation completed with an error

![image](https://user-images.githubusercontent.com/805238/111081544-e1427080-8514-11eb-9c59-355a8e158a18.png)

The overall impression is that the template has never been tested and too much stuffed with the extra unnecessary functionality

**Comment by Dmdv** [comment]
Seems to be fixed with a proper module name but still...
There's also todonotes app that remains after creating a project

**Comment by sagikazarmark** [comment]
> The overall impression is that the template has never been tested and too much stuffed with the extra unnecessary functionality

I don't actually use the init script much, but I don't think it's fair to say it's untested. Whether there is too much stuff in it is subjective. This project serves as more like an example and I used it as basis for dozens of projects.

It's not a RAD framework, you can't use it without actually knowing and understanding how it works.

Looks like the solution is trivial to your problem and you actually solved it. Thanks for letting me know about the init script failure.
