### ISSUE TITLE
Make sure that application imports are always in a separate group

### ISSUE THREAD

**Issue by sagikazarmark** [sagikazarmark/modern-go-application#51]
When running the init script in the boilerplate, import name might break alphabetical order.

This has been fixed for now in #50 , but we should make sure it continues to work in the future as well.

- [x] Check IDE settings
- [x] Write some test/lint rule?

**Comment by sagikazarmark** [comment]
Goland can automatically format imports.

**Comment by sagikazarmark** [comment]
Golang CI (goimports) supports this rule.

**Comment by lpuskas** [comment]
👍
