### ISSUE TITLE
The name of the jaeger collectorendpoint environment variable is wrong

### ISSUE THREAD

**Issue by lpuskas** [sagikazarmark/modern-go-application#61]
The above mentioned configuration needs to be changed either in the jaeger config or the environment variable so that viper properly unmarshalls it into the application configuration
( Field name in the Config struct: CollectorEndpoint, env var name: v.SetDefault("instrumentation.jaeger.endpoint", "http://localhost:14268")
 
I am happy to push the PR if this is valid ...

**Comment by sagikazarmark** [comment]
PRs are always welcome!
