### ISSUE TITLE
Is there any tutorial or more detailed document for gokit beginner?

### ISSUE THREAD

**Issue by leopku** [sagikazarmark/modern-go-application#83]
Thanks for this awesome project.

Before I came into this project, I have no experience of gokit.
I want to use this project to learn gokit and start my first gokit project.
Is there any tutorial or more detailed document for gokit beginner to do things like steps of creating new service etc.

Best regards.

**Comment by sagikazarmark** [comment]
Thanks for reaching out, I'm glad you like the project.

Unfortunately there isn't really a documentation for this project...yet.

For examples, you could check the project website: http://gokit.io/

**Comment by leopku** [comment]
Thanks a lot.

**Comment by leopku** [comment]
Another question, is `modern-go-application` support multi api/service other than `todo` in one application?
If yes, How can I do it?

I had review the codes of `https://github.com/go-kit/kit/tree/master/examples/shipping`, it seems simple. And it's clean how to add a new api/service.
I want to add another apis/services in this awesome project, but I had no idea now.

Appreciate for your answer.
